# Generated by Django 4.0 on 2021-12-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_category_alter_project_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='is project pinned'),
        ),
    ]
