# Generated by Django 4.0 on 2021-12-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-pub_datetime',), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
    ]
