# Generated by Django 4.0 on 2021-12-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_like_project_alter_like_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_like'),
        ),
    ]
