name: Django CI

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        db: postgres
        python-version: [3.7, 3.8, 3.9]
        include:
          - db: postgres
            db_port: 5432
    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: django
          POSTGRES_PASSWORD: django
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-veresion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi
    - name: Run Tests
      env:
        DJANGO_DB_HOST: 127.0.0.1
        DJANGO_DB_PORT: ${{ matrix.db_port }}
        DJANGO_DB_USEr: django
        DJANGO_DB_PASSWORD: django
      run: |
        python manage.py test